### ISSUE TITLE
django unit tests are broken

### ISSUE THREAD

**Issue by mhrivnak** [rbarrois/python-semanticversion#22]
It appears that when django 1.7 or newer is installed, some unit tests have errors. I tested with 1.4.20, 1.5.12, and 1.6.11 which all pass.

Examples below are using a fresh python 2.7.9 virtualenv, with the stated django version, and South==1.0.2

On 1.7.8, this happens:

```
======================================================================
ERROR: setUpClass (tests.test_django.DbInteractingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mhrivnak/git/python-semanticversion/tests/test_django.py", line 182, in setUpClass
    cls.old_state = DjangoTestSuiteRunner().setup_databases()
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/test/runner.py", line 109, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/test/runner.py", line 299, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/db/backends/creation.py", line 377, in create_test_db
    test_flush=True,
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 93, in call_command
    app_name = get_commands()[name]
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 73, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
AppRegistryNotReady: Apps aren't loaded yet.

======================================================================
ERROR: test_serialization (tests.test_django.DjangoFieldTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mhrivnak/git/python-semanticversion/tests/test_django.py", line 97, in test_serialization
    obj1, obj2 = serializers.deserialize('json', data)
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 81, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 75, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 93, in Deserializer
    Model = _get_model(d["model"])
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 156, in _get_model
    return apps.get_model(model_identifier)
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
DeserializationError: Models aren't loaded yet.

======================================================================
ERROR: test_serialization_partial (tests.test_django.DjangoFieldTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mhrivnak/git/python-semanticversion/tests/test_django.py", line 109, in test_serialization_partial
    obj1, obj2 = serializers.deserialize('json', data)
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 81, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 75, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 93, in Deserializer
    Model = _get_model(d["model"])
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 156, in _get_model
    return apps.get_model(model_identifier)
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
DeserializationError: Models aren't loaded yet.

======================================================================
ERROR: test_freezing_app (tests.test_django.SouthTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mhrivnak/git/python-semanticversion/tests/test_django.py", line 147, in test_freezing_app
    frozen = south.creator.freezer.freeze_apps('django_test_app')
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/south/creator/freezer.py", line 26, in freeze_apps
    for model in models.get_models(models.get_app(app)):
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 54, in alias
    return getattr(loading, function_name)(*args, **kwargs)
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 372, in get_app
    models_module = self.get_app_config(app_label).models_module
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 146, in get_app_config
    self.check_apps_ready()
  File "/home/mhrivnak/pythons/semver-d17/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
AppRegistryNotReady: Apps aren't loaded yet.

----------------------------------------------------------------------
Ran 57 tests in 0.027s

FAILED (errors=4, skipped=1)
```

And on 1.8.2, this...

```
$ python setup.py test
running test
running egg_info
writing semantic_version.egg-info/PKG-INFO
writing top-level names to semantic_version.egg-info/top_level.txt
writing dependency_links to semantic_version.egg-info/dependency_links.txt
reading manifest file 'semantic_version.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
writing manifest file 'semantic_version.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    test_suite='tests',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mhrivnak/pythons/semver/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/mhrivnak/pythons/semver/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/home/mhrivnak/pythons/semver/local/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/mhrivnak/pythons/semver/local/lib/python2.7/site-packages/setuptools/command/test.py", line 37, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_django'
```

The problem on 1.8.2 appears to be the result of this import failing: https://github.com/rbarrois/python-semanticversion/blob/v2.4.1/tests/test_django.py#L176

That class was removed as of django 1.8: https://docs.djangoproject.com/en/1.8/releases/1.8/

If you fix that import to instead use django.test.runner.DiscoverRunner, then the same errors from 1.7.8 appear.

**Comment by mhrivnak** [comment]
This backward-incompatible change in 1.7 explains some of the problems: https://docs.djangoproject.com/en/dev/releases/1.7/#app-loading-changes
