### ISSUE TITLE
Optional VersionField that is null breaks Django ORM on retrieval

### ISSUE THREAD

**Issue by hugorodgerbrown** [rbarrois/python-semanticversion#33]
Hi there - running on Django 1.8. I have a model that has an optional VersionField (null=True, blank=True). If I save the model, I can see in the database that the value is stored as the string 'None', which then subsequently fails on rehydration:

```
Traceback (most recent call last):
  File "/Projects/python-semanticversion/tests/test_django.py", line 56, in test_null_version
    self.assertRaises(ValueError, models.PartialVersionModel.objects.get(id=obj.id))
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/query.py", line 255, in iterator
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/base.py", line 489, in from_db
    new = cls(*values)
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/base.py", line 410, in __init__
    setattr(self, field.attname, val)
  File "/Users/hugo/.virtualenvs/semver/lib/python2.7/site-packages/django/db/models/fields/subclassing.py", line 44, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File "/Users/hugo/Projects/src/github.com/yunojuno/python-semanticversion/semantic_version/django_fields.py", line 61, in to_python
    return base.Version(value, partial=self.partial)
  File "/Users/hugo/Projects/src/github.com/yunojuno/python-semanticversion/semantic_version/base.py", line 75, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/Users/hugo/Projects/src/github.com/yunojuno/python-semanticversion/semantic_version/base.py", line 192, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: u'None'
```

You can test this with the following test:

```python
def test_optional_field(self):
    """Test storing a null value in optional VersionField."""
    obj = models.PartialVersionModel()
    obj.save()
    self.assertIsNone(obj.optional)
    self.assertRaises(ValueError, models.PartialVersionModel.objects.get, id=obj.id)
```

This makes some sense, as the `VersionField.to_python` method doesn't check for 'None':

```
def to_python(self, value):
    """Converts any value to a base.Version field."""
    if value is None or value == '':
        return value
    if isinstance(value, base.Version):
        return value
    if self.coerce:
        return base.Version.coerce(value, partial=self.partial)
    else:
        return base.Version(value, partial=self.partial)
```

Possibly looking at the `BaseSemVerField.get_prep_value` method, which just str's the object value:

```python
def get_prep_value(self, obj):
    return str(obj)
```

This would turn `None` into `'None'`

**Comment by hugorodgerbrown** [comment]
The PR above should fix this. Includes tests, which were proven to fail on the existing master.

**Comment by rbarrois** [comment]
I've just merged the PR, thanks for finding the issue and building the fix :)
