### ISSUE TITLE
TypeError on matching to Spec('~1')

### ISSUE THREAD

**Issue by awcrosby** [rbarrois/python-semanticversion#71]
I can make a specifier with `'~1'` but when doing a `match` or `select` on it, it causes a `TypeError`. I tried to provide the relevant details below, thanks!

```
Successfully installed semantic-version-2.6.0
(sv) awc:env$ python3
Python 3.6.8 (default, Jan 27 2019, 09:00:23)
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.                                  
>>> import semantic_version
>>> v = semantic_version.Version('1.1.2')
>>> s_major = semantic_version.Spec('~1')
>>> s_minor = semantic_version.Spec('~1.1')
>>> s_minor.match(v)
True
>>> s_major.match(v)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/awc/code/env/sv/lib/python3.6/site-packages/semantic_version/base.py", line 515, in match
    return all(spec.match(version) for spec in self.specs)
  File "/home/awc/code/env/sv/lib/python3.6/site-packages/semantic_version/base.py", line 515, in <genexpr>
    return all(spec.match(version) for spec in self.specs)
  File "/home/awc/code/env/sv/lib/python3.6/site-packages/semantic_version/base.py", line 478, in match
    return self.spec <= version < self.spec.next_minor()
  File "/home/awc/code/env/sv/lib/python3.6/site-packages/semantic_version/base.py", line 104, in next_minor
    '.'.join(str(x) for x in [self.major, self.minor + 1, 0]))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
>>> s_major
<Spec: (<SpecItem: ~ Version('1', partial=True)>,)>
```

**Comment by rbarrois** [comment]
This has been fixed in version 2.7.0, thanks for the report!
```python
>>> import semantic_version
>>> semantic_version.Version('1.1.2') in semantic_version.SimpleSpec('~1')
True
```
